CREATE TABLE T_STATECODE(
ID  INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
STATECODE INTEGER,
STATENAME  VARCHAR(50),
STATEABBR VARCHAR(3)
);

CREATE INDEX idx_statecode ON T_STATECODE(STATECODE);

CREATE TABLE T_SUBCODE(
ID  INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
STATECODEID INTEGER,
SUBCODE INTEGER,
SUBCODEDESCRIPTION  VARCHAR(25),
SUBCODETYPE VARCHAR(25),
CONSTRAINT fk_sub_state FOREIGN KEY(STATECODEID) REFERENCES T_STATECODE(ID)
);

CREATE TABLE T_BORDERPOINT(
ID  BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
STATECODEID INTEGER,
SUBCODEID INTEGER,
LATITUDE  DECIMAL(10,5) NOT NULL,
LONGITUDE DECIMAL(10,5) NOT NULL,
CONSTRAINT fk_brd_state FOREIGN KEY(STATECODEID) REFERENCES T_STATECODE(ID),
CONSTRAINT fk_brd_sub FOREIGN KEY(SUBCODEID) REFERENCES T_SUBCODE(ID)
);

CREATE INDEX idx_brd_statesub ON T_BORDERPOINT(STATECODEID, SUBCODEID);

CREATE TABLE T_CUSTOMFEATURE(
ID  BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
FEATURENAME VARCHAR(50),
FEATURECLASS VARCHAR(25),
STATECODEID INTEGER,
LATITUDE DECIMAL(10,5),
LONGITUDE DECIMAL(10,5),
CONSTRAINT fk_cst_stcd FOREIGN KEY(STATECODEID) REFERENCES T_STATECODE(ID)
);